apiVersion: v1
kind: Pod
metadata:
  name: opa
  labels:
    app: opa
    owner: prai
    run: prai
spec:
  containers:
    - name: opa
      image: testserver:5000/opa:0.0.7
      ports:
        - name: opa-http
          containerPort: 8181
        - name: nodeexport-http
          containerPort: 9100
      volumeMounts:
        - name: opa-data
          mountPath: /opt/policies
  initContainers:
    - name: install
      image: bitnami/git
      command:
        - git
        - "clone"
        - "https://github.com/rai-prashanna/policy"
        - "/work-dir"
      volumeMounts:
        - name: opa-data
          mountPath: "/work-dir"
    - name: git-sync
      image: k8s.gcr.io/git-sync:v3.1.3
      volumeMounts:
        - name: opa-data
          mountPath: /data
      env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/rai-prashanna/policy" 
        - name: GIT_SYNC_BRANCH
          value: "main" ##repo-branch
        - name: GIT_SYNC_ROOT
          value: /data
        - name: GIT_SYNC_DEST
          value: "hello" ##path-where-you-want-to-clone
        - name: GIT_SYNC_PERIOD
          value: "20"
        - name: GIT_SYNC_ONE_TIME
          value: "false"
  dnsPolicy: Default
  volumes:
    - name: opa-data
      emptyDir: {}
