apiVersion: v1
kind: Service
metadata:
  name: opa-service
  labels:
    app: opa-service
    owner: prai
    run: prai
spec:
  type: NodePort
  selector:
    app: opa
    owner: prai
    run: prai
  ports:
    - name: opa
      port: 9191
      nodePort: 32323
      targetPort: 8181
    - name: nodeexporter
      port: 9292
      nodePort: 32555
      targetPort: 9100
