apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opa-data-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: opa-data