{
 "title": "Open Policy Agent Metrics",
 "description": "Open Policy Agents Runtime metrics",
 "tags": [
  "go",
  "golang",
  "opa"
 ],
 "time": { "from": "2023-05-10T16:15:34.592Z", "to": "2023-05-10T18:15:34.592Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(go_goroutines, namespace)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(go_goroutines{namespace=\"$namespace\",  app=~\"opa.*\"}, instance)"
   },
   { "name": "cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"} - go_memstats_other_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{instance}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total - go_memstats_frees_total{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Object and Pointers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rates of Allocation per $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"testserver:32323\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated Per $interval",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=\"testserver:32323\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences per $interval",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{instance=\"testserver:32323\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory In Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes obtained from system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes allocated & still in-use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes waiting to be used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_idle_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes in use ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes released to OS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_released_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Objects allocated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Off-heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mspan bytes usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes used for mspan obtained from system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes used for mcache obtained from system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes in use by mcache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes used for garbage collection system metadata",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_sys_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes used by the profiling bucket hash table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes when next garbage collection will take place",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes used for other system allocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_other_sys_bytes - go_memstats_other_sys_bytes",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{instance}}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=\"testserver:32323\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[$interval])) / sum(rate(http_request_duration_seconds_count[$interval]))"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": "50th Quantile (Median)"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": "90th Quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": "95th Quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": "99th Quantile"
    }
   ]
  }
 ]
}